version: "3.7"

volumes:
  postgres_data:
  mina_deps:
  mina_build:
  mina_node_modules:

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql

  mina:
    build: { context: ., target: development }
    command: mix phx.server
    depends_on: [postgres]
    ports: [4000:4000]
    volumes:
      - mina_deps:/app/deps
      - mina_build:/app/_build
      - mina_node_modules:/app/assets/node_modules
      - .:/app
