name: Continuous integration
on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.base.yml:docker-compose.ci.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker images
        run: docker-compose pull

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build application
        run: docker-compose build

      - name: Setup environment
        run: |
          docker-compose up --no-start
          docker-compose run mina mix do ecto.create, ecto.migrate 2> /dev/null

      - name: Check formatting
        run: docker-compose run mina mix format --check-formatted 2> /dev/null

      - name: Run linter
        run: docker-compose run mina mix credo 2> /dev/null

      - name: Run tests
        run: docker-compose run mina mix test --trace 2> /dev/null

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build release
        run: docker build . --target production --build-arg MIX_ENV=prod
