name: Continuous integration
on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.base.yml:docker-compose.ci.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application
        id: build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          image_name: mina-ci
          build_extra_args: --target build --build-arg MIX_ENV=test
          push_git_tag: true

      - name: Setup environment
        run: |
          docker tag ${{ steps.build.outputs.FULL_IMAGE_NAME }} mina-ci
          docker-compose up --no-start
          docker-compose run mina mix do ecto.create, ecto.migrate 2> /dev/null

      - name: Check formatting
        run: docker-compose run mina mix format --check-formatted 2> /dev/null

      - name: Run linter
        run: docker-compose run mina mix credo 2> /dev/null

      - name: Run tests
        run: docker-compose run mina mix test --trace 2> /dev/null

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build release
        id: build_release
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          image_name: mina
          image_tag: ${{ github.sha }}
          build_extra_args: --target production --build-arg MIX_ENV=prod
          push_git_tag: true

  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Setup Docker
        run: echo ${{ github.token }} | docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Pull image
        run: docker pull docker.pkg.github.com/${{ github.repository }}/mina:${{ github.sha }}

      - name: Tag image
        run: docker tag docker.pkg.github.com/${{ github.repository }}/mina:${{ github.sha }} docker.pkg.github.com/${{ github.repository }}/mina

      - name: Push image
        run: docker push docker.pkg.github.com/${{ github.repository }}/mina
